
# List of CPP File #
LOCAL_SRC_FILES := main.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/AppDelegate.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/HelloWorldScene.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/SampleTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDHelper.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDMenu.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDMenuTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDSuite.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/ButtonTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/EditBoxTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/ExampleTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/LabelTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/ScrollTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/TDDHelperTest.cpp


#Include DIR #
LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(CLASS_PATH)
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/libs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/TDDLib
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/UnitTest
